# Generated by Django 4.0.3 on 2022-03-14 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_is_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile_picture',
            field=models.ImageField(default='user_default.png', upload_to='users/'),
        ),
    ]
