# Generated by Django 4.0.3 on 2022-03-15 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_customuser_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='profile_picture',
            field=models.ImageField(default='user_default.png', upload_to='users/'),
        ),
    ]
