# Generated by Django 4.0.3 on 2022-03-03 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_teacher_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='profile_picture',
            field=models.ImageField(default='default_pic.png', upload_to='users/'),
        ),
    ]
