# Generated by Django 4.0.3 on 2022-03-03 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_remove_customuser_is_teacher_teacher_is_teacher'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacher',
            old_name='is_teacher',
            new_name='is_staff',
        ),
    ]
