# Generated by Django 4.0.3 on 2022-03-03 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_rename_is_teacher_teacher_is_staff'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacher',
            old_name='is_staff',
            new_name='is_teacher',
        ),
    ]
