# Generated by Django 4.0.3 on 2022-03-03 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_rename_is_staff_teacher_is_teacher'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacher',
            old_name='is_teacher',
            new_name='is_active',
        ),
    ]
