# Generated by Django 4.0.3 on 2022-03-03 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_remove_teacher_is_active_alter_customuser_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='is_teacher',
            field=models.BooleanField(default=True),
        ),
    ]
