# Generated by Django 4.0.3 on 2022-03-03 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_teacher_is_teacher'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='is_teacher',
        ),
    ]
