# Generated by Django 4.0.3 on 2022-03-21 15:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0008_alter_coursereview_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursereview',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coursereview', to='course.course'),
        ),
    ]
