# Generated by Django 4.0.3 on 2022-03-23 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0012_alter_coursereview_comment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursereview',
            name='comment',
            field=models.TextField(default=''),
        ),
    ]
